optimizers:
  scinol:
  - {beta: 1}
  - {epsilon_scaled: True}
  scinol2:
  - {epsilon_scaled: True}
  scinola:
  scinol2a:
  scinolb:
  scinol2b:
  prescinol:
  - {epsilon_scaled: 'd'}
  - {epsilon_scaled: 'dt'}


models:
  LR:
    - {init0: True}


datasets:
  - UCI_Census


train_batchsize: 1
epochs: 10
times: 1
train_histograms: False
train_logs: False
no_tqdm: False
tblogdir: tb_logs_linear