optimizers:
  scinol:
    - {beta: 1}
    - {epsilon_scaled: True}
  scinol2:
    - {epsilon_scaled: True}
  scinola:
  scinol2a:
  scinolb:
  scinol2b:
  prescinol:
    - {epsilon_scaled: 'd'}
    - {epsilon_scaled: 'dt'}

models:
  LR:
    - {init0: True}


datasets:
  - Mnist
  - UCI_Madelon
  - UCI_Bank
  - UCI_Census
  - UCI_Covertype
  - PennShuttle


train_batchsize: 1
epochs: 10
times: 1
train_histograms: False
train_logs: False
no_tqdm: True