optimizers:
  scinol:
#  - {}
#  - {beta: 1}
#  - {epsilon_scaled: True}
#  scinol2:
#  - {epsilon_scaled: True}
#  - {}
#  scinola:
#  scinol2a:
#  scinolb:
#  scinol2b:
#  prescinol:
#  - {}
#  - {epsilon_scaled: 'd'}
#  - {epsilon_scaled: 'dt'}
#  prescinol2:
#  adam:
#    - {learning_rate: 1.0 }
#    - {learning_rate: 0.1 }
#    - {learning_rate: 0.5 }
#    - {learning_rate: 0.01 }
#    - {learning_rate: 0.05 }
#    - {learning_rate: 0.001 }
#    - {learning_rate: 0.005 }
#    - {learning_rate: 0.0001 }
#    - {learning_rate: 0.0005 }
#    - {learning_rate: 0.00001 }
#  adagrad:
#    - {learning_rate: 1.0 }
#    - {learning_rate: 0.1 }
#    - {learning_rate: 0.5 }
#    - {learning_rate: 0.01 }
#    - {learning_rate: 0.05 }
#    - {learning_rate: 0.001 }
#    - {learning_rate: 0.005 }
#    - {learning_rate: 0.0001 }
#    - {learning_rate: 0.0005 }
#    - {learning_rate: 0.00001 }
#  adadelta:
#    - {learning_rate: 1.0 }
#    - {learning_rate: 0.1 }
#    - {learning_rate: 0.5 }
#    - {learning_rate: 0.01 }
#    - {learning_rate: 0.05 }
#    - {learning_rate: 0.001 }
#    - {learning_rate: 0.005 }
#    - {learning_rate: 0.0001 }
#    - {learning_rate: 0.0005 }
#    - {learning_rate: 0.00001 }
#  rmsprop:
#    - {learning_rate: 1.0 }
#    - {learning_rate: 0.1 }
#    - {learning_rate: 0.5 }
#    - {learning_rate: 0.01 }
#    - {learning_rate: 0.05 }
#    - {learning_rate: 0.001 }
#    - {learning_rate: 0.005 }
#    - {learning_rate: 0.0001 }
#    - {learning_rate: 0.0005 }
#    - {learning_rate: 0.00001 }
#  sgd:
#    - {learning_rate: 1.0 }
#    - {learning_rate: 0.1 }
#    - {learning_rate: 0.5 }
#    - {learning_rate: 0.01 }
#    - {learning_rate: 0.05 }
#    - {learning_rate: 0.001 }
#    - {learning_rate: 0.005 }
#    - {learning_rate: 0.0001 }
#    - {learning_rate: 0.0005 }
#    - {learning_rate: 0.00001 }

models:
  CNN:
    - { name: cnn, filters_nums: [32,32,32], kernel_sizes: [6,4,2], strides: [2,2,1], fc_layers: [1000,1000],dropout: 0.9 }

dataset: Mnist
train_batchsize: 128

epochs: 20
times: 1
tblogdir: tb_logs_conv