optimizers:
  scinol:
    - {}
    - {beta: 1}
  scinol2:
  cocob:
models:
#  CNN:
#    - { fc_layers: [1000], filters_nums: [32,32,32], kernel_sizes: [5,3,2], strides: [3,2,1] }
  NN:
    - { layers: [1000,1000],  dropout: 0 }
#  LR:
#    - {}
#    - {init0: True}
#

datasets:
#- SynthNormal
#- SynthScaled
#  - SynthOutliers
  - Mnist
#  - UCI_Madelon
#  - UCI_Bank
#  - UCI_Census
#  - UCI_Covertype
#  - PennShuttle
#  - PennShuttle
#  - PennPoker
#  - PennSleep
#  - PennFars
#  - PennKddcup
#  - PennConnect4
#  - PennShuttle

train_batchsize: 256
epochs: 5
times: 1
train_histograms: False
train_logs: False