optimizers:
  scinol:
  scinol2:
  cocob:
models:
#  - nn_1000_500
#  - nn_1000_500_elu
#  - cnn_simple
#  - cnn_simple_elu
#  - lr
  - lr0

datasets:
#- SynthNormal
#- SynthScaled
#  - SynthOutliers
#  - Mnist
  - UCI_Madelon
  - UCI_Bank
  - UCI_Census
  - UCI_Covertype
  - PennShuttle
#  - PennShuttle
#  - PennPoker
#  - PennSleep
#  - PennFars
#  - PennKddcup
#  - PennConnect4
#  - PennShuttle

train_batchsize: 256
epochs: 20
times: 1
train_histograms: False
train_logs: False