#optimizers:
#  scinol:
#    - {}
#    - {beta: 1}
#    - {scale_epsilon: True}
#  scinol2:
#    - {}
#    - {scale_epsilon: True}
#  scinola:
#  scinol2a:
#  scinolb:
#  scinol2b:
#
##  cocob:
##  adam:
#models:
##  CNN:
##    - { fc_layers: [1000], num_outputs: [32,32,32], kernel_sizes: [5,3,2], strides: [3,2,1] }
#  NN:
#    - { layers: [1000,1000], dropout: 0.9 }
##  LR:
##    - {}
##    - {init0: True}
##
#
#datasets:
##- SynthNormal
##- SynthScaled
##  - SynthOutliers
#  - Mnist
##  - UCI_Madelon
##  - UCI_Bank
##  - UCI_Census
##  - UCI_Covertype
##  - PennShuttle
##  - PennShuttle
##  - PennPoker
##  - PennSleep
##  - PennFars
##  - PennKddcup
##  - PennConnect4
##  - PennShuttle
#
#train_batchsize: 256
#epochs: 20
#times: 1
#train_histograms: False
#train_logs: True
optimizers:
  adam:
    - {learning_rate: 1.0 }



models:
  NN:
    - { layers: [1000,1000], dropout: 0.9 }



datasets:
  - UCI_Covertype


train_batchsize: 128
epochs: 10
times: 1
train_histograms: False
train_logs: False
no_tqdm: False
tblogdir: tb_logs_nn_b128