optimizers:
#  COCOBOptimizer:
#    - {alpha: 0}
#    - {alpha: 100}
#  AdalbertOptimizer:
  ScInOLOptimizer:
#  ScInOL2Optimizer:
# tf.train.AdagradOptimizer:
#    - {learning_rate: 0.00075 }
#  tf.train.GradientDescentOptimizer:
#    - {learning_rate: 0.01 }


#  tf.train.AdadeltaOptimizer:
#    - {learning_rate: 1.0}
#    - {learning_rate: 0.001}

#  tf.train.RMSPropOptimizer:
#    - {learning_rate: 0.0005 }
#  tf.train.AdagradOptimizer:
#    - {learning_rate: 0.00075 }
##  MetagradOptimizer:
#    - {num_etas: 20, D: 0.15}
#    - {num_etas: 10, D: 0.15}
#    - {num_etas: 5, D: 0.15}
models:
#  - nn_1000_500
#  - nn_1000_500_elu
#  - cnn_simple
#  - cnn_simple_elu
  - lr0
datasets:
  - Mnist

train_batchsize: 100

one_hot: True
epochs: 30
times: 1
train_histograms: False